import 'dart:convert';
import 'dart:ffi';
import 'dart:typed_data';

import 'package:convert/convert.dart';
import 'package:ffi/ffi.dart';
import 'package:wallet_test/ffi_impl/generated_bindings.dart';

const _oneBtcInSatoshi = 100000000;

class Utils {
  Utils._();

  static Pointer<Char> toNativeChar(String string, {Allocator allocator = malloc}) {
    final units = utf8.encode(string);
    final Pointer<Uint8> result = allocator<Uint8>(units.length + 1);
    final Uint8List nativeString = result.asTypedList(units.length + 1);
    nativeString.setAll(0, units);
    nativeString[units.length] = 0;
    return result.cast<Char>();
  }

  static String bytesToHex(List<int> bytes) => hex.encode(Uint8List.fromList(bytes));

  static String btcToSatoshi(String btc) => (double.parse(btc) * _oneBtcInSatoshi).round().toString();

  static String satoshiToBtc(String satoshi) => (double.parse(satoshi) / _oneBtcInSatoshi).toString();

  static String getCoinName(TWCoinType coinType) => switch (coinType) {
        TWCoinType.TWCoinTypeAeternity => 'Aeternity',
        TWCoinType.TWCoinTypeAion => 'Aion',
        TWCoinType.TWCoinTypeBinance => 'Binance',
        TWCoinType.TWCoinTypeBitcoin => 'Bitcoin',
        TWCoinType.TWCoinTypeBitcoinCash => 'Bitcoin Cash',
        TWCoinType.TWCoinTypeBitcoinGold => 'Bitcoin Gold',
        TWCoinType.TWCoinTypeCallisto => 'Callisto',
        TWCoinType.TWCoinTypeCardano => 'Cardano',
        TWCoinType.TWCoinTypeCosmos => 'Cosmos',
        TWCoinType.TWCoinTypePivx => 'Pivx',
        TWCoinType.TWCoinTypeDash => 'Dash',
        TWCoinType.TWCoinTypeDecred => 'Decred',
        TWCoinType.TWCoinTypeDigiByte => 'DigiByte',
        TWCoinType.TWCoinTypeDogecoin => 'Dogecoin',
        TWCoinType.TWCoinTypeEOS => 'EOS',
        TWCoinType.TWCoinTypeWAX => 'WAX',
        TWCoinType.TWCoinTypeEthereum => 'Ethereum',
        TWCoinType.TWCoinTypeEthereumClassic => 'Ethereum Classic',
        TWCoinType.TWCoinTypeFIO => 'FIO',
        TWCoinType.TWCoinTypeGoChain => 'GoChain',
        TWCoinType.TWCoinTypeGroestlcoin => 'Groestlcoin',
        TWCoinType.TWCoinTypeICON => 'ICON',
        TWCoinType.TWCoinTypeIoTeX => 'IoTeX',
        TWCoinType.TWCoinTypeKava => 'Kava',
        TWCoinType.TWCoinTypeKin => 'Kin',
        TWCoinType.TWCoinTypeLitecoin => 'Litecoin',
        TWCoinType.TWCoinTypeMonacoin => 'Monacoin',
        TWCoinType.TWCoinTypeNebulas => 'Nebulas',
        TWCoinType.TWCoinTypeNULS => 'NULS',
        TWCoinType.TWCoinTypeNano => 'Nano',
        TWCoinType.TWCoinTypeNEAR => 'NEAR',
        TWCoinType.TWCoinTypeNimiq => 'Nimiq',
        TWCoinType.TWCoinTypeOntology => 'Ontology',
        TWCoinType.TWCoinTypePOANetwork => 'POA Network',
        TWCoinType.TWCoinTypeQtum => 'Qtum',
        TWCoinType.TWCoinTypeXRP => 'XRP',
        TWCoinType.TWCoinTypeSolana => 'Solana',
        TWCoinType.TWCoinTypeStellar => 'Stellar',
        TWCoinType.TWCoinTypeTezos => 'Tezos',
        TWCoinType.TWCoinTypeTheta => 'Theta',
        TWCoinType.TWCoinTypeThunderCore => 'ThunderCore',
        TWCoinType.TWCoinTypeNEO => 'NEO',
        TWCoinType.TWCoinTypeViction => 'Viction',
        TWCoinType.TWCoinTypeTron => 'Tron',
        TWCoinType.TWCoinTypeVeChain => 'VeChain',
        TWCoinType.TWCoinTypeViacoin => 'Viacoin',
        TWCoinType.TWCoinTypeWanchain => 'Wanchain',
        TWCoinType.TWCoinTypeZcash => 'Zcash',
        TWCoinType.TWCoinTypeFiro => 'Firo',
        TWCoinType.TWCoinTypeZilliqa => 'Zilliqa',
        TWCoinType.TWCoinTypeZelcash => 'Zelcash',
        TWCoinType.TWCoinTypeRavencoin => 'Ravencoin',
        TWCoinType.TWCoinTypeWaves => 'Waves',
        TWCoinType.TWCoinTypeTerra => 'Terra',
        TWCoinType.TWCoinTypeTerraV2 => 'TerraV2',
        TWCoinType.TWCoinTypeHarmony => 'Harmony',
        TWCoinType.TWCoinTypeAlgorand => 'Algorand',
        TWCoinType.TWCoinTypeKusama => 'Kusama',
        TWCoinType.TWCoinTypePolkadot => 'Polkadot',
        TWCoinType.TWCoinTypeFilecoin => 'Filecoin',
        TWCoinType.TWCoinTypeMultiversX => 'MultiversX',
        TWCoinType.TWCoinTypeBandChain => 'BandChain',
        TWCoinType.TWCoinTypeSmartChainLegacy => 'SmartChain Legacy',
        TWCoinType.TWCoinTypeSmartChain => 'SmartChain',
        TWCoinType.TWCoinTypeTBinance => 'TBinance',
        TWCoinType.TWCoinTypeOasis => 'Oasis',
        TWCoinType.TWCoinTypePolygon => 'Polygon',
        TWCoinType.TWCoinTypeTHORChain => 'THORChain',
        TWCoinType.TWCoinTypeBluzelle => 'Bluzelle',
        TWCoinType.TWCoinTypeOptimism => 'Optimism',
        TWCoinType.TWCoinTypeZksync => 'Zksync',
        TWCoinType.TWCoinTypeArbitrum => 'Arbitrum',
        TWCoinType.TWCoinTypeECOChain => 'ECOChain',
        TWCoinType.TWCoinTypeAvalancheCChain => 'Avalanche C-Chain',
        TWCoinType.TWCoinTypeXDai => 'XDai',
        TWCoinType.TWCoinTypeFantom => 'Fantom',
        TWCoinType.TWCoinTypeCryptoOrg => 'CryptoOrg',
        TWCoinType.TWCoinTypeCelo => 'Celo',
        TWCoinType.TWCoinTypeRonin => 'Ronin',
        TWCoinType.TWCoinTypeOsmosis => 'Osmosis',
        TWCoinType.TWCoinTypeECash => 'ECash',
        TWCoinType.TWCoinTypeIOST => 'IOST',
        TWCoinType.TWCoinTypeCronosChain => 'Cronos Chain',
        TWCoinType.TWCoinTypeSmartBitcoinCash => 'Smart Bitcoin Cash',
        TWCoinType.TWCoinTypeKuCoinCommunityChain => 'KuCoin Community Chain',
        TWCoinType.TWCoinTypeBitcoinDiamond => 'Bitcoin Diamond',
        TWCoinType.TWCoinTypeBoba => 'Boba',
        TWCoinType.TWCoinTypeSyscoin => 'Syscoin',
        TWCoinType.TWCoinTypeVerge => 'Verge',
        TWCoinType.TWCoinTypeZen => 'Zen',
        TWCoinType.TWCoinTypeMetis => 'Metis',
        TWCoinType.TWCoinTypeAurora => 'Aurora',
        TWCoinType.TWCoinTypeEvmos => 'Evmos',
        TWCoinType.TWCoinTypeNativeEvmos => 'Native Evmos',
        TWCoinType.TWCoinTypeMoonriver => 'Moonriver',
        TWCoinType.TWCoinTypeMoonbeam => 'Moonbeam',
        TWCoinType.TWCoinTypeKavaEvm => 'Kava Evm',
        TWCoinType.TWCoinTypeKlaytn => 'Klaytn',
        TWCoinType.TWCoinTypeMeter => 'Meter',
        TWCoinType.TWCoinTypeOKXChain => 'OKX Chain',
        TWCoinType.TWCoinTypeStratis => 'Stratis',
        TWCoinType.TWCoinTypeKomodo => 'Komodo',
        TWCoinType.TWCoinTypeNervos => 'Nervos',
        TWCoinType.TWCoinTypeEverscale => 'Everscale',
        TWCoinType.TWCoinTypeAptos => 'Aptos',
        TWCoinType.TWCoinTypeNebl => 'Nebl',
        TWCoinType.TWCoinTypeHedera => 'Hedera',
        TWCoinType.TWCoinTypeSecret => 'Secret',
        TWCoinType.TWCoinTypeNativeInjective => 'Native Injective',
        TWCoinType.TWCoinTypeAgoric => 'Agoric',
        TWCoinType.TWCoinTypeTON => 'TON',
        TWCoinType.TWCoinTypeSui => 'Sui',
        TWCoinType.TWCoinTypeStargaze => 'Stargaze',
        TWCoinType.TWCoinTypePolygonzkEVM => 'Polygon zkEVM',
        TWCoinType.TWCoinTypeJuno => 'Juno',
        TWCoinType.TWCoinTypeStride => 'Stride',
        TWCoinType.TWCoinTypeAxelar => 'Axelar',
        TWCoinType.TWCoinTypeCrescent => 'Crescent',
        TWCoinType.TWCoinTypeKujira => 'Kujira',
        TWCoinType.TWCoinTypeIoTeXEVM => 'IoTeX EVM',
        TWCoinType.TWCoinTypeNativeCanto => 'Native Canto',
        TWCoinType.TWCoinTypeComdex => 'Comdex',
        TWCoinType.TWCoinTypeNeutron => 'Neutron',
        TWCoinType.TWCoinTypeSommelier => 'Sommelier',
        TWCoinType.TWCoinTypeFetchAI => 'Fetch AI',
        TWCoinType.TWCoinTypeMars => 'Mars',
        TWCoinType.TWCoinTypeUmee => 'Umee',
        TWCoinType.TWCoinTypeCoreum => 'Coreum',
        TWCoinType.TWCoinTypeQuasar => 'Quasar',
        TWCoinType.TWCoinTypePersistence => 'Persistence',
        TWCoinType.TWCoinTypeAkash => 'Akash',
        TWCoinType.TWCoinTypeNoble => 'Noble',
        TWCoinType.TWCoinTypeScroll => 'Scroll',
        TWCoinType.TWCoinTypeRootstock => 'Rootstock',
        TWCoinType.TWCoinTypeThetaFuel => 'Theta Fuel',
        TWCoinType.TWCoinTypeConfluxeSpace => 'Conflux eSpace',
        TWCoinType.TWCoinTypeAcala => 'Acala',
        TWCoinType.TWCoinTypeAcalaEVM => 'Acala EVM',
        TWCoinType.TWCoinTypeOpBNB => 'OpBNB',
        TWCoinType.TWCoinTypeNeon => 'Neon',
        TWCoinType.TWCoinTypeBase => 'Base',
        TWCoinType.TWCoinTypeSei => 'Sei',
        TWCoinType.TWCoinTypeArbitrumNova => 'Arbitrum Nova',
        TWCoinType.TWCoinTypeLinea => 'Linea',
        TWCoinType.TWCoinTypeGreenfield => 'Greenfield',
        TWCoinType.TWCoinTypeMantle => 'Mantle',
        TWCoinType.TWCoinTypeZenEON => 'Zen EON',
        TWCoinType.TWCoinTypeInternetComputer => 'Internet Computer',
        TWCoinType.TWCoinTypeTia => 'Tia',
        TWCoinType.TWCoinTypeMantaPacific => 'Manta Pacific',
        TWCoinType.TWCoinTypeNativeZetaChain => 'Native Zeta Chain',
        TWCoinType.TWCoinTypeZetaEVM => 'Zeta EVM',
        TWCoinType.TWCoinTypeDydx => 'Dydx',
        TWCoinType.TWCoinTypeMerlin => 'Merlin',
        TWCoinType.TWCoinTypeLightlink => 'Lightlink',
        TWCoinType.TWCoinTypeBlast => 'Blast',
        TWCoinType.TWCoinTypeBounceBit => 'Bounce Bit',
        TWCoinType.TWCoinTypeZkLinkNova => 'ZkLink Nova',
        _ => 'Unknown',
      };
}
